<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Returns the list of replicated entity types.
 *
 * @return string[]
 *   List of entity type ids.
 */
function contentpool_remote_register_replicated_types() {
  return ['node', 'media', 'file', 'paragraph', 'taxonomy_term'];
}

/**
 * Implements hook_entity_insert().
 */
function contentpool_remote_register_entity_insert(EntityInterface $entity) {
  if (in_array($entity->getEntityTypeId(), contentpool_remote_register_replicated_types())) {
    \Drupal::service('contentpool_remote_register.push_manager')->pushToRegisteredRemotes();
  }
}

/**
 * Implements hook_entity_update().
 */
function contentpool_remote_register_entity_update(EntityInterface $entity) {
  contentpool_remote_register_entity_insert($entity);
}
